name: example
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  bloc: ^8.0.0
  equatable: ^2.0.0
  flow_builder:
    path: ../
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0

dev_dependencies:
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
